spring:
  datasource:
    url: jdbc:mysql:jdbc:mysql://localhost:3306/blood_donor_db
    username: root
    password: Surya@217
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

jwt:
  secret: aVeryLongSecretKeyForJwtAuthenticationInBloodDonorManagementSystemWhichShouldBeAtLeast256BitsLong
  expiration: 86400000 # 24 hours

cors:
  allowed-origins: http://localhost:5173 # Vite default port
